backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "meny"
    label: "Meny"
    files:
      - file: "site_data/meny.json"
        label: "Kafémeny"
        name: "meny"
        fields:
          - label: "Kaffe & varme drikker"
            name: "hotdrinks"
            widget: "list"
            fields:
              - { label: "Navn", name: "title", widget: "string" }
              - { label: "Pris", name: "price", widget: "string" }
              - { label: "Plantebasert", name: "vegan", widget: "boolean", required: false, default: false }

          - label: "Frokost & lunsj"
            name: "lunch"
            widget: "list"
            fields:
              - { label: "Navn", name: "title", widget: "string" }
              - { label: "Pris", name: "price", widget: "string" }
              - { label: "Plantebasert", name: "vegan", widget: "boolean", required: false, default: false }

          - label: "Søtt & kaldt"
            name: "dessert"
            widget: "list"
            fields:
              - { label: "Navn", name: "title", widget: "string" }
              - { label: "Pris", name: "price", widget: "string" }
              - { label: "Plantebasert", name: "vegan", widget: "boolean", required: false, default: false }

  - name: "aapningstider"
    label: "Åpningstider"
    files:
      - file: "site_data/hours.json"
        label: "Åpningstider"
        name: "hours"
        fields:
          - { label: "Hverdager – åpner",  name: "weekdays_open",  widget: "string", default: "09:00" }
          - { label: "Hverdager – stenger", name: "weekdays_close", widget: "string", default: "18:00" }
          - { label: "Lørdag – åpner",     name: "saturday_open",  widget: "string", default: "09:00" }
          - { label: "Lørdag – stenger",    name: "saturday_close", widget: "string", default: "17:00" }
          - { label: "Notis (valgfri)",     name: "note",           widget: "string", required: false }

  - name: "dagens"
    label: "Dagens lunsj"
    files:
      - file: "site_data/dagens.json"
        label: "Dagens lunsj"
        name: "dagens"
        fields:
          - { label: "Overskrift", name: "title", widget: "string", default: "Dagens lunsj" }
          - label: "Retter"
            name: "items"
            widget: "list"
            fields:
              - { label: "Navn", name: "title", widget: "string" }
              - { label: "Pris", name: "price", widget: "string" }
          - { label: "Oppdatert", name: "updated", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
